### ISSUE TITLE
Custom /proc path

### ISSUE THREAD

**Issue by mnmtanish** [soldair/node-procfs-stats#4]
Hi,
I forked this repo because I wanted this to work when `/proc` is mounted somewhere else. We were doing something with docker. Anyways, if you think it can be useful for others I can send a pull request.

**Comment by soldair** [comment]
neat yeah i would love to see a pr

**Comment by mnmtanish** [comment]
Fixed https://github.com/soldair/node-procfs-stats/commit/feca2a940805b31f9e7d5c0bd07c4e3f8d3d5303

**Comment by soldair** [comment]
added you as a colaborator. contributing guidelines are based on those of webtorrent https://github.com/feross/webtorrent/blob/master/CONTRIBUTING.md this is an open opensource project. welcome.
